// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIW6GOvXMtCm7Qk11do_uWFRkQXTCs92s',
    appId: '1:864669987106:web:4677bea75e02415289f57b',
    messagingSenderId: '864669987106',
    projectId: 'hellofire-d7946',
    authDomain: 'hellofire-d7946.firebaseapp.com',
    storageBucket: 'hellofire-d7946.firebasestorage.app',
    measurementId: 'G-5YQVBEG0Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVC_3_2NpFemKrydBbMEQZ47-xUo65C4',
    appId: '1:864669987106:android:00f10178ef0057f689f57b',
    messagingSenderId: '864669987106',
    projectId: 'hellofire-d7946',
    storageBucket: 'hellofire-d7946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMZW4HJrDT0gGijoPn02l8U-sxYLBqdfM',
    appId: '1:864669987106:ios:dfb29dc64064ff5a89f57b',
    messagingSenderId: '864669987106',
    projectId: 'hellofire-d7946',
    storageBucket: 'hellofire-d7946.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMZW4HJrDT0gGijoPn02l8U-sxYLBqdfM',
    appId: '1:864669987106:ios:dfb29dc64064ff5a89f57b',
    messagingSenderId: '864669987106',
    projectId: 'hellofire-d7946',
    storageBucket: 'hellofire-d7946.firebasestorage.app',
    iosBundleId: 'com.example.fire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIW6GOvXMtCm7Qk11do_uWFRkQXTCs92s',
    appId: '1:864669987106:web:5de6fd5ab4dc61e689f57b',
    messagingSenderId: '864669987106',
    projectId: 'hellofire-d7946',
    authDomain: 'hellofire-d7946.firebaseapp.com',
    storageBucket: 'hellofire-d7946.firebasestorage.app',
    measurementId: 'G-1M2MSBEYGT',
  );
}
